aahalive/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("menucard/", include("menucard.urls")),
        path("", include("website.urls")),
        path("web/", include("web.urls")),
        path("official/", include("official.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

official/urls.py
from . import views
from django.urls import path


app_name = "official"

urlpatterns = [
    path("login-page", views.loginPage, name="loginPage"),
    path("logout-resto", views.logout_resto, name="logout_resto"),
    path("", views.home, name="home"),
    path("resturant_list", views.resturantList, name="resturant_list"),
    path("resturant_details/<int:id>", views.resturantDetails, name="resturant_details"),
    path("create_user", views.creatUsers, name="create_user"),
    path("banneradding", views.bannerPage, name="banneradding"),
    path("product-banner", views.productBanner, name="productbanner"),
    path("video", views.videoAdding, name="video"),
]

web/urls.py
from . import views
from django.urls import path


app_name = "web"

urlpatterns = [
    path("", views.home, name="home"),
    # catagory
    path("category", views.category, name="category"),
    path("categorynamevalidation", views.categoryNameValidation, name="categorynamevalidation"),
    path("getcategory/<int:id>", views.getCategory, name="getcategory"),
    path("editcategory", views.editCategory, name="editcategory"),
    path("deletecatgory/<int:id>", views.deleteCategory, name="deletecatgory"),
    # subcategory
    path("subcategory/<int:id>", views.subCategory, name="subcategory"),
    path("getsubcategory/<int:id>", views.getSubcategory, name="getsubcategory"),
    path("deletesubcatgory/<int:id>", views.deleteSubCategory, name="deletesubcatgory"),
    path("product/<int:id>", views.product, name="product"),
    path("product-show/<int:id>", views.productshow, name="productshow"),
    path("productinactive/<int:id>", views.productNotavailable, name="productinactive"),
    path("productactive/<int:id>", views.productavailable, name="productactive"),
    path("deleteproduct/<int:id>", views.deleteProduct, name="deleteproduct"),
    path("banner", views.banner, name="banner"),
    path("profile", views.profile, name="profile"),
    path("settings", views.settings, name="settings"),
    path("socialmedia", views.socialMedialinks, name="socialmedia"),
    # table
    path("table-On/<int:id>", views.tableOn, name="tableOn"),
    path("table-off/<int:id>", views.tableOff, name="tableOff"),
]

website/urls.py
from . import views
from django.urls import path


app_name = "website"

urlpatterns = [path("", views.websitehome, name="websitehome"), path("registration", views.registration, name="registration")]

official/models.py
# Create your models here.

official/views.py
from aahalive.decorators import auth_official
from website.models import FrontBanner
from website.models import ProductPageBanner
from website.models import Restaurant
from website.models import Video

from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render


# Create your views here.


# LOGIN
def loginPage(request):
    if request.method == "POST":
        phone = request.POST["phone"]
        password = request.POST["password"]
        user = authenticate(request, phone=phone, password=password)
        if user is not None:
            if user.restaurant:
                login(request, user)
                return redirect("web:home")
            elif user.is_superuser:
                login(request, user)
                return redirect("official:home")
            else:
                return redirect("official:loginPage")
        else:
            return redirect("official:loginPage")
    return render(request, "official/login.html")


# HOME PAGE
@auth_official
@login_required(login_url="/official/login-page")
def home(request):
    resto_count = Restaurant.objects.all().count()
    all_resto = Restaurant.objects.all()[:5]
    banner = ProductPageBanner.objects.all()[:2]
    context = {"is_home": True, "resto_count": resto_count, "all_resto": all_resto, "banner": banner}
    return render(request, "official/home.html", context)


# RESTURANT LIST
@auth_official
@login_required(login_url="/official/login-page")
def resturantList(request):
    all_resturants = Restaurant.objects.all().order_by("restaurant_name")
    context = {"is_resto": True, "all_resturants": all_resturants}
    return render(request, "official/resturant_list.html", context)


# RESTURANT DETAILS
@auth_official
@login_required(login_url="/official/login-page")
def resturantDetails(request, id):
    resto_details = Restaurant.objects.get(id=id)
    data = {
        "resto_name": resto_details.restaurant_name,
        "creator_name": resto_details.creator_name,
        "email": resto_details.email,
        "phone": resto_details.phone,
        "district": resto_details.district,
        "state": resto_details.state,
        "address": resto_details.address,
    }
    return JsonResponse(data)


# USER CREATION
@auth_official
@login_required(login_url="/official/login-page")
def creatUsers(request):
    if request.method == "POST":
        cname = request.POST["cname"]
        email = request.POST["email"]
        district = request.POST["district"]
        rname = request.POST["rname"]
        phone = request.POST["phone"]
        state = request.POST["state"]
        address = request.POST["address"]
        password = request.POST["password"]

        resto_exist = Restaurant.objects.filter(phone=phone).exists()
        if not resto_exist:
            new_resto = Restaurant(creator_name=cname, restaurant_name=rname, email=email, phone=phone, password=password, district=district, state=state, address=address)
            new_resto.save()
            return render(request, "official/create_user.html", {"status": 1})
        else:
            return render(request, "official/create_user.html", {"status": 0})
    context = {"is_users": True}
    return render(request, "official/create_user.html", context)


# BANNER SECTION
@auth_official
@login_required(login_url="/official/login-page")
def bannerPage(request):
    if request.method == "POST":
        print("front-image")
        front_image = request.FILES["front-image"]
        front_banner = FrontBanner(image=front_image)
        front_banner.save()
    all_front_banner = FrontBanner.objects.all()
    all_product_banner = ProductPageBanner.objects.all()
    context = {"is_banner": True, "all_front_banner": all_front_banner, "all_product_banner": all_product_banner}
    return render(request, "official/banneradding.html", context)


# PRODUCT BANNER
@auth_official
@login_required(login_url="/official/login-page")
def productBanner(request):
    if request.method == "POST":
        product_image = request.FILES["product-image"]
        product_banner = ProductPageBanner(image=product_image)
        product_banner.save()
    return redirect("official:banneradding")


# VIDEO
def videoAdding(request):
    all_video = Video.objects.all()
    if request.method == "POST":
        video = request.FILES["video"]
        new_video = Video(video=video)
        new_video.save()
    context = {"is_video": True, "all_video": all_video}
    return render(request, "official/video.html", context)


# LOGOUT
def logout_resto(request):
    logout(request)
    return redirect("official:loginPage")

templates/official/banneradding.html
{% extends 'official/partials/base.html' %}
{% load static %}
{% block content %}

<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Banner Adding</h3>
            <ul class="breadcrumb">
                <li class=""><a href="{% url 'official:home' %}">Dashboard / </a>
                </li>
                <li class="breadcrumb-item active">Banner</li>
            </ul>
        </div>
        <div class="col-auto">
            <a href="" class="btn btn-primary me-1" data-bs-toggle="modal" data-bs-target="#front-page">
                <i class="fas fa-plus"></i> Front-page Banner
            </a>
            <a href="" class="btn btn-primary me-1" data-bs-toggle="modal" data-bs-target="#product-page">
                <i class="fas fa-plus"></i> Product-page Banner
            </a>
        </div>
    </div>
</div>


<!-- <div class="row mt-4">
    <div class="col-sm-6 col-lg-2 col-xl-4 col-2 d-flex">
        <div class="card invoices-grid-card w-100">
            <div class="card-middle text-center">
                <h2 class="card-middle-avatar text-center">
                    <a href="">
                        <img class="avatar text-center avatar-sm images me-2 avatar-img " src="{% static 'web/img/building.png' %}" alt="User Image"> 
                    </a>
                </h2>
            </div>
        </div>
    </div>
</div> -->


<div class="col-md-12">
    <div class="card bg-white">
        <div class="card-header">
            <h5 class="card-title">Basic tabs</h5>
        </div>
        <div class="card-body">
            <ul class="nav nav-tabs">
                <li class="nav-item"><a class="nav-link active" href="#basictab1"
                        data-bs-toggle="tab">Front Banner</a></li>
                <li class="nav-item"><a class="nav-link" href="#basictab2"
                        data-bs-toggle="tab">Product Banner</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane show active" id="basictab1">
                    
                    <div class="row">
                        {% for f in all_front_banner %}
                        <div class="col-lg-3">
                            <div class="card invoices-grid-card w-100">
                                <div class="card-middle text-center">
                                    <h2 class="card-middle-avatar text-center">
                                        <a href="">
                                            <img class="avatar text-center avatar-sm images me-2 avatar-img " src="{{f.image.url}}" alt="User Image"> 
                                        </a>
                                    </h2>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    
                </div>

                <div class="tab-pane" id="basictab2">
                    <div class="row">
                    {% for p in all_product_banner %}
                        <div class="col-lg-3">
                            <div class="card invoices-grid-card w-100">
                                <div class="card-middle text-center">
                                    <h2 class="card-middle-avatar text-center">
                                        <a href="">
                                            <img class="avatar text-center avatar-sm images me-2 avatar-img " src="{{p.image.url}}" alt="User Image"> 
                                        </a>
                                    </h2>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>




<!-- Front Page -->
<div class="modal custom-modal fade invoices-preview" id="front-page" role="dialog" name="fbanner">
    <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="card invoice-info-card">
                            <div class="card-header">
                                <h5 class="card-title">Add Category</h5>
                            </div>
                            <div class="card-body pb-0">
                                <form action="#" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group row">
                                        <label class="col-form-label col-md-4">File Input</label>
                                        <div class="col-md-8">
                                            <input class="form-control" type="file" name="front-image">
                                        </div>
                                    </div>
                                    <div class="text-end mt-4">
                                        <button type="submit" class="btn btn-primary">Add Banner</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- product page -->
<div class="modal custom-modal fade invoices-preview" id="product-page" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="card invoice-info-card">
                            <div class="card-header">
                                <h5 class="card-title">Add Category</h5>
                            </div>
                            <div class="card-body pb-0">
                                <form action="{% url 'official:productbanner' %}" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group row">
                                        <label class="col-form-label col-md-4">File Input</label>
                                        <div class="col-md-8">
                                            <input class="form-control" type="file" name="product-image">
                                        </div>
                                    </div>
                                    <div class="text-end mt-4">
                                        <button type="submit" class="btn btn-primary">Add Banner</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock %}

templates/official/home.html
{% extends 'official/partials/base.html' %}
{% load static %}
{% block content %}

<style>
    .banner {
    vertical-align: middle;
    width: 100% !important;
    height: 210px !important;
}
</style>




<div class="row">
    <div class="col-lg-6">
        <div class="row">
            <div class="col-xl-6 col-sm-6 col-lg-6 col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="dash-widget-header">
                            <span class="dash-widget-icon bg-1">
                                <i class="fas fa-dollar-sign"></i>
                            </span>
                            <div class="dash-count">
                                <div class="dash-title">Amount Due</div>
                                <div class="dash-counts">
                                    <p>1,642</p>
                                </div>
                            </div>
                        </div>
                        <div class="progress progress-sm mt-3">
                            <div class="progress-bar bg-5" role="progressbar" style="width: 75%"
                                aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xl-6 col-sm-6 col-lg-6 col-12">
                <div class="card">
                    <div class="card-body">
                        <div class="dash-widget-header">
                            <span class="dash-widget-icon bg-2">
                                <i class="fas fa-users"></i>
                            </span>
                            <div class="dash-count">
                                <div class="dash-title">Customers</div>
                                <div class="dash-counts">
                                    <p>{{resto_count}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="progress progress-sm mt-3">
                            <div class="progress-bar bg-6" role="progressbar" style="width: 65%"
                                aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    
        <div class="row">
            <div class="col-md-12 col-sm-6">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col">
                                <h5 class="card-title">Resturant List</h5>
                            </div>
                            <div class="col-auto">
                                <a href="{% url 'official:resturant_list' %}" class="btn-right btn btn-sm btn-outline-primary">
                                    View All
                                </a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-stripped table-hover">
                                <thead class="thead-light">
                                    <tr>
                                        <th>Name</th>
                                        <th>Phone</th>
                                        <th>Registered Date</th>
                                        <th>Email</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for resto in all_resto %}
                                    <tr>
                                        <td>
                                            <h2 class="table-avatar">
                                                <a href=""><img
                                                        class="avatar avatar-sm me-2 avatar-img rounded-circle"
                                                        src="{% static 'web/img/building.png' %}"
                                                        alt="User Image">{{resto.restaurant_name}}</a>
                                            </h2>
                                        </td>
                                        <td>{{resto.phone}}</td>
                                        <td>23 Nov 2020</td>
                                        <td>{{resto.email}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="col-lg-12 banner">
            {% for b in banner %}
            <img src="{{b.image.url}}" alt="" class="banner" style="padding: 5px;">
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/official/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>Aaha Menu</title>

    <link rel="shortcut icon" href="{% static 'menucard/images/logo/aha1.png' %}">

    <link rel="stylesheet" href="{% static 'web/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'web/plugins/fontawesome/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/plugins/fontawesome/css/all.min.css' %}">

    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">
</head>

<body>

    <div class="main-wrapper login-body">
        <div class="login-wrapper">
            <div class="container">
                <div class="loginbox">
                    <div class="login-right">
                        <div class="login-right-wrap">
                            <h1>Login</h1>
                            <p class="account-subtitle">Access to our dashboard</p>
                            <form action="" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="form-control-label">Phone Number</label>
                                    <input type="text" name="phone" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label class="form-control-label">Password</label>
                                    <div class="pass-group">
                                        <input type="password" class="form-control pass-input" name="password">
                                        <span class="fas fa-eye toggle-password"></span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-6">
                                            <div class="custom-control custom-checkbox">
                                                <input type="checkbox" class="custom-control-input" id="cb1">
                                                <label class="custom-control-label" for="cb1">Remember me</label>
                                            </div>
                                        </div>
                                        <div class="col-6 text-end">
                                            <!-- <a class="forgot-link" href="forgot-password.html">Forgot Password ?</a> -->
                                        </div>
                                    </div>
                                </div>
                                <button class="btn btn-lg btn-block btn-primary w-100" type="submit">Login</button>
                                

                                

                                <div class="text-center dont-have">Don't have an account yet? <a
                                        href="{% url 'website:registration' %}">Register</a></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <script src="{% static 'web/js/jquery-3.6.0.min.js' %}"></script>

    <script src="{% static 'web/js/bootstrap.bundle.min.js' %}"></script>

    <script src="{% static 'web/js/feather.min.js' %}"></script>

    <script src="{% static 'web/js/script.js' %}"></script>
</body>

</html>

templates/official/resturant_list.html
{% extends 'official/partials/base.html' %}
{% load static %}
{% block content %}



<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Resturant List</h3>
            <ul class="breadcrumb">
                <li class=""><a href="{% url 'official:home' %}">Dashboard / </a>
                </li>
                <li class="breadcrumb-item active">Resturant List</li>
            </ul>
        </div>
        <div class="col-auto">
            <a href="{% url 'official:create_user' %}" class="btn btn-primary me-1">
                <i class="fas fa-plus"></i>
            </a>
        </div>
    </div>
</div>



<div class="row">
    <div class="col-sm-12">
        <div class="card card-table">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-center table-hover datatable">
                        <thead class="thead-light">
                            <tr>
                                <th>Name</th>
                                <th>Creator Name</th>
                                <th>Email</th>
                                <th>Phone</th>
                                <th>Place</th>
                                <th>Status</th>
                                <th class="text-end">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for resto in all_resturants %}
                            <tr>
                                <td>
                                    <h2 class="table-avatar">
                                        <a href="" class="avatar avatar-sm me-2"><img
                                                class="avatar-img rounded-circle"
                                                src="{% static 'web/img/building.png' %}"
                                                alt="User Image"></a>
                                        <a href="">
                                            {{resto.restaurant_name|capfirst}} <span>{{resto.phone}}</span>
                                        </a>
                                    </h2>
                                </td>
                                <td>{{resto.creator_name|capfirst}}</td>
                                <td>
                                    {{resto.email}}
                                </td>
                                <td>{{resto.phone}}</td>
                                <td>{{resto.district|capfirst}}</td>
                                <td><span class="badge badge-pill bg-success-light">Active</span></td>
                                <td class="text-end">
                                    <a href="" onclick="FranchiseDetails({{resto.id}})"  data-bs-toggle="modal" data-bs-target="#view"
                                        class="btn btn-sm btn-white text-primary me-2"><i
                                            class="far fa-edit me-1"></i> View</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>



<!-- Quick View Modal Box Start -->
<div class="modal fade theme-modal view-modal" id="view" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg modal-fullscreen-sm-down">
        <div class="modal-content">
            <div class="modal-header p-0">
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </div>
            <div class="modal-body">
                <div class="row g-sm-4 g-2">
                    <div class="col-lg-6">
                        <div class="slider-image">
                            <img src="{% static 'web/img/building.png' %}"
                                class="img-fluid blur-up lazyload" alt="">
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="right-sidebar-modal">
                            <h4 class="title-name" id="resto_name"></h4>
                            <h4 class="price">Creator : <span id="c_name"></span></h4>
                            <div class="product-detail">
                                <h4>Resturant Details :</h4>
                                <h6 > email : &nbsp; <span id="email"></span></h6>
                                <h6> phone : &nbsp;<span id="phone"></span></h6>
                                <h6> District : &nbsp;<span id="dist"></span></h6>
                                <h6> State : &nbsp;<span id="state"></span></h6>
                                <h6> Address : &nbsp;<span id="address"></span></h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    function FranchiseDetails(id) {
        $.ajax({
            url: "/official/resturant_details/" +id,
            type: 'GET',

            success: function (responce) {
                $('#resto_name').html(responce.resto_name)
                $('#c_name').html(responce.creator_name)
                $('#email').html(responce.email)
                $('#phone').html(responce.phone)
                $('#dist').html(responce.district)
                $('#state').html(responce.state)
                $('#address').html(responce.address)

            }

        })

    }

</script>


{% endblock %}