aahalive/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("menucard/", include("menucard.urls")),
        path("", include("website.urls")),
        path("web/", include("web.urls")),
        path("official/", include("official.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

web/urls.py
from . import views
from django.urls import path


app_name = "web"

urlpatterns = [
    path("", views.home, name="home"),
    # catagory
    path("category", views.category, name="category"),
    path("categorynamevalidation", views.categoryNameValidation, name="categorynamevalidation"),
    path("getcategory/<int:id>", views.getCategory, name="getcategory"),
    path("editcategory", views.editCategory, name="editcategory"),
    path("deletecatgory/<int:id>", views.deleteCategory, name="deletecatgory"),
    # subcategory
    path("subcategory/<int:id>", views.subCategory, name="subcategory"),
    path("getsubcategory/<int:id>", views.getSubcategory, name="getsubcategory"),
    path("deletesubcatgory/<int:id>", views.deleteSubCategory, name="deletesubcatgory"),
    path("product/<int:id>", views.product, name="product"),
    path("product-show/<int:id>", views.productshow, name="productshow"),
    path("productinactive/<int:id>", views.productNotavailable, name="productinactive"),
    path("productactive/<int:id>", views.productavailable, name="productactive"),
    path("deleteproduct/<int:id>", views.deleteProduct, name="deleteproduct"),
    path("banner", views.banner, name="banner"),
    path("profile", views.profile, name="profile"),
    path("settings", views.settings, name="settings"),
    path("socialmedia", views.socialMedialinks, name="socialmedia"),
    # table
    path("table-On/<int:id>", views.tableOn, name="tableOn"),
    path("table-off/<int:id>", views.tableOff, name="tableOff"),
]

templates/web/banner.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}


<div class="page-header">
    <div class="row align-items-center">
        <div class="col">
            <h3 class="page-title">Banner Adding</h3>
            <ul class="breadcrumb">
                <li class=""><a href="{% url 'web:home' %}">Dashboard / </a>
                </li>
                <li class="breadcrumb-item active">Banner</li>
            </ul>
        </div>
        <div class="col-auto">
            <a href="" class="btn btn-primary me-1" data-bs-toggle="modal" data-bs-target="#front-page">
                <i class="fas fa-plus"></i> Home Banner
            </a>

        </div>
    </div>
</div>


<div class="col-md-12">
    <div class="card bg-white">
        <div class="card-header">

        </div>
        <div class="card-body">
            <div class="col-lg-3">
                <div class="card invoices-grid-card w-100">
                    <div class="card-middle text-center">
                        <h2 class="card-middle-avatar text-center">
                            {% for b in all_banner %}
                            <a href="">
                                <img class="avatar text-center avatar-sm images me-2 avatar-img " src="{{b.image.url}}"
                                    alt="User Image">
                            </a>
                            {% endfor %}
                        </h2>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


<!-- Front Page -->
<div class="modal custom-modal fade invoices-preview" id="front-page" role="dialog" name="fbanner">
    <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="card invoice-info-card">
                            <div class="card-header">
                                <h5 class="card-title">Add Banner</h5>
                            </div>
                            <div class="card-body pb-0">
                                <form action="#" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group row">
                                        <label class="col-form-label col-md-4">File Input</label>
                                        <div class="col-md-8">
                                            <span>Size : 1135 x 300 px</span>
                                            <input class="form-control" type="file" name="home-image">
                                        </div>
                                    </div>
                                    <div class="text-end mt-4">
                                        <button type="submit" class="btn btn-primary">Add Banner</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

templates/web/category.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}

<style>
    /*  */
    .profile-img-wrap.edit-img {
        border-radius: 50%;
        margin: 0 auto 30px;
        position: relative;
    }

    .profile-img-wrap {
        height: 120px;
        position: absolute;
        width: 120px;
        background: #ffffff;
        overflow: hidden;
    }

    img {
        max-width: 100%;
        height: auto;
        vertical-align: middle;
    }

    .profile-img-wrap .fileupload {
        background: rgba(33, 33, 33, 0.5);
        border: none;
        padding: 3px 10px;
        border-radius: 0;
        position: absolute;
        right: 0;
        bottom: 0;
        left: 0;
    }

    .profile-img-wrap .fileupload .btn-text {
        color: #ffffff;
    }

    .profile-img-wrap .fileupload .upload {
        cursor: pointer;
        filter: alpha(opacity=0);
        font-size: 20px;
        opacity: 0;
        margin: 0;
        padding: 5px;
        position: absolute;
        top: -3px;
        right: -3px;
    }
</style>


<div class="page-header">
    <div class="row">
        <div class="col-sm-6">
            <h3 class="page-title">Category List</h3>
            <ul class="breadcrumb">
                <li class=""><a href="index.html">Dashboard / </a>
                </li>
                <li class="breadcrumb-item active"> Category</li>
            </ul>
        </div>

        <div class="col-sm-6">
            <div class="card invoices-tabs-card">
                <div class="card-body card-body pt-0 pb-0">
                    <div class="invoices-main-tabs border-0 pb-0">
                        <div class="row align-items-center">
                            <div class="col-lg-12 col-md-12">
                                <div class="invoices-settings-btn invoices-settings-btn-one">
                                    <a href="" class="btn" data-bs-toggle="modal" data-bs-target="#invoices_preview">
                                        <i class="fa fa-circle-plus"></i> &nbsp;&nbsp; New category
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<div class="row">
    {% for category in categories %}
        <div class="col-sm-6 col-lg-2 col-xl-2 col-6 d-flex">
            <div class="card invoices-grid-card w-100">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <a href="" class="invoice-grid-link">{{category.name}}</a>
                    <div class="dropdown dropdown-action">
                        <a href="#" class="action-icon dropdown-toggle sm" data-bs-toggle="dropdown"
                            aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <!-- <a class="dropdown-item" onclick="DataGets({{category.id}})" data-bs-toggle="modal" data-bs-target="#edit_category"><i
                                    class="far fa-edit me-2"></i>Edit</a> -->
                            <a class="dropdown-item"  onclick="deletecategory({{category.id}})"><i
                                    class="far fa-trash-alt me-2"></i>Delete</a>
                        </div>
                    </div>
                </div>
                <div class="card-middle text-center">
                    <h2 class="card-middle-avatar text-center">
                        <a href="">
                            <img class="avatar text-center avatar-sm images me-2 avatar-img " src="{{category.icon.url}}" alt="User Image"> 
                        </a>
                    </h2>
                </div>
                <div class="card-footer">
                    <div class="row align-items-center">
                        <div class="col-auto">
                            <a href="{% url 'web:subcategory' category.id %}" type="button" class="btn btn-sm btn-block btn-outline-primary">Sub Category</a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>

<!-- ADD CATEGORY -->
<div class="modal custom-modal fade invoices-preview" id="invoices_preview" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="card invoice-info-card">
                            <div class="card-header">
                                <h5 class="card-title">Add Category</h5>
                            </div>
                            <div class="card-body pb-0">
                                <form action="#" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group row">
                                        <label class="col-form-label col-md-4">Category Name</label>
                                        <div class="col-md-8">
                                            <input type="text" class="form-control" required name="cat-name" id="cat_name" onchange="catageoryName()">
                                            <span id="catogry"></span>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-form-label col-md-4">File Input</label>
                                        <div class="col-md-8">
                                            <input class="form-control" type="file" name="cat-image">
                                        </div>
                                    </div>
                                    <div class="text-end mt-4">
                                        <button type="submit" class="btn btn-primary">Add Category</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- EDIT PRODUCT -->
<div class="modal custom-modal fade invoices-preview" id="edit_category" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="card invoice-info-card">
                            <div class="card-header">
                                <h5 class="card-title">Edit Product</h5>
                            </div>
                            <div class="card-body pb-0">
                                <form id="editcategoryform" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <div class="form-group row">
                                        <div class="profile-img-wrap edit-img">
                                            <img class="inline-block" src=""
                                                id="image" alt="user">
                                            <div class="fileupload btn">
                                                <span class="btn-text">edit</span>
                                                <input class="upload" name="photo" type="file"  id="iimage">
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-form-label col-md-4">Product Name</label>
                                        <div class="col-md-8">
                                            <input type="text" class="form-control" name="name" value="" id="pname">
                                        </div>
                                    </div>

                                    <input type="number" id="fid" name="fid" hidden>
                                    <div class="text-end mt-4">
                                        <button type="submit" class="btn btn-primary">Edit Product</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    function catageoryName(){
        $.ajax({
            url: '/web/categorynamevalidation',
            type:'GET',
            data:{
                'cat_name':$('#cat_name').val()
            },
            success: function (responce) {
                $('#catogry').html(responce.msg)
                // window.location.reload()
            }
        })
    }



    function DataGets(id) {
        alert(id)
        $.ajax({
            url: "/web/getcategory/" +id,
            type: 'GET',

            success: function (responce) {
                $('#fid').val(id)
                $('#pname').val(responce.name)
                $('#image').attr("src", responce.image)

            }

        })

    }


    $(document).ready(function () {
        
        $("#editcategoryform").submit(function (e) {
            // var data = $("#categorysave").serializeArray();
            var formData = new FormData(e.target);
            e.preventDefault();
            console.log(formData)
            $.ajax({
                url: "/web/editcategory",
                type: "POST",
                data: formData,
                contentType: false,
                processData: false,
                cache: false,
                success: function (responce) {
                    Swal.fire({
                        position: 'top-center',
                        icon: 'success',
                        title: 'Your Category Has Been Edited',
                        showConfirmButton: false,
                        timer: 3000
                      })
                      setInterval('location.reload()', 3000);   
                 
                }
                
            })
        })
    });
</script>
<script>
    function deletecategory(id) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                Swal.fire(
                    'Deleted!',
                    'Your file has been deleted.',
                    'success'
                )
                window.location.href = "/web/deletecatgory/" + id
            }
        })
    }
</script>
{% endblock %}

templates/web/home.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}


<div class="row">
    <div class="col-lg-12 mt-2">
        <h5>Welcome {{user.restaurant|capfirst}} ...!</h5>
    </div>
</div>


<div class="row mt-3">
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card">
            <div class="card-body">
                <div class="dash-widget-header">
                    <span class="dash-widget-icon bg-1">
                        <i class="fa fa-bowl-food"></i>
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Category</div>
                        <div class="dash-counts">
                            <p>{{category_count}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card">
            <div class="card-body">
                <div class="dash-widget-header">
                    <span class="dash-widget-icon bg-2">
                        <i class="fa fa-bread-slice"></i>
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Products</div>
                        <div class="dash-counts">
                            <p>{{product_count}}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card">
            <div class="card-body">
                <div class="dash-widget-header">
                    <span class="dash-widget-icon bg-3">
                        <i class="fas fa-file-alt"></i>
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Hot Deals</div>
                        <div class="dash-counts">
                            <p>None</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 col-12">
        <div class="card">
            <div class="card-body">
                <div class="dash-widget-header">
                    <!-- <span class="dash-widget-icon bg-2">
                       <h4>Table</h4>
                    </span> -->
                    <div class="dash-count">
                        <div class="dash-title">Table</div>
                        {% if qr_code.restaurant.is_table == True %}
                        <div class="dash-counts">
                            <a href="{% url 'web:tableOff' qr_code.restaurant.id %}" class="btn-sm btn-danger">TurnOff</a>
                        </div>
                        {% else %}
                        <div class="dash-counts">
                            <a href="{% url 'web:tableOn' qr_code.restaurant.id %}" class="btn-sm btn-success">TurnOn</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- <div class="col-xl-3 col-sm-6 col-12">
        <div class="card">
            <div class="card-body">
                <div class="dash-widget-header">
                    <span class="dash-widget-icon bg-4">
                        <i class="far fa-file"></i>
                    </span>
                    <div class="dash-count">
                        <div class="dash-title">Estimates</div>
                        <div class="dash-counts">
                            <p>2,150</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
</div>

<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col">
                        <h5 class="card-title">Product List</h5>
                    </div>
                    <div class="col-auto">
                        <a href="{% url 'web:category' %}" class="btn-right btn btn-sm btn-outline-primary">
                            View All
                        </a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-stripped table-hover">
                        <thead class="thead-light">
                            <tr>
                                <th>Product</th>
                                <th>Category</th>
                                <th>Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in all_product %}
                            <tr>
                                <td>
                                    <h2 class="table-avatar">
                                        <a href=""><img
                                                class="avatar avatar-sm me-2 avatar-img rounded-circle"
                                                src="{{product.image.url}}"
                                                alt="User Image">{{product.name}}</a>
                                    </h2>
                                </td>
                                <td>{{product.subcategory.Category.name}}</td>
                                <td>₹118</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-sm-6 text-center">
        <div class="card">
            <div class="card-body">
                <h3>QRCODE FOR MENU CARD</h3>
                <span>..... Scan here to get your menucard details .....</span>
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col-lg-12 col-12">
                            <img src="{{qr_code.image.url}}" alt="" width="200px">
                        </div>
                    </div>
                    <a href="{{qr_code.image.url}}" download class="btn badge-pill bg-primary-light m-t-10" ><i class="fa fa-download"></i> Download From Here</a>
                </div>
            </div>
        </div>
        
    </div>
    
    
</div>


{% endblock %}

templates/web/subcategory.html
{% extends 'web/partials/base.html' %}
{% load static %}
{% block content %}


<div class="page-header">
    <div class="row">
        <div class="col-sm-6">
            <h3 class="page-title">Category List</h3>
            <ul class="breadcrumb">
                <li class="{% url 'web:home' %}"><a href="">Dashboard / </a></li>
                <li class=""><a href="{% url 'web:category' %}">&nbsp; Category / </a></li>
                <li class="breadcrumb-item active">&nbsp; SubCategory</li>
            </ul>
        </div>
        <div class="col-sm-6">
            <div class="card invoices-tabs-card">
                <div class="card-body card-body pt-0 pb-0">
                    <div class="invoices-main-tabs border-0 pb-0">
                        <div class="row align-items-center">
                            <div class="col-lg-12 col-md-12">
                                <div class="invoices-settings-btn invoices-settings-btn-one">
                                    <a href="" class="btn" data-bs-toggle="modal" data-bs-target="#add_subcategory">
                                        <i class="fa fa-plus-circle"></i>&nbsp; New Subcategory
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="row">
    {% for subcategory in subcategories %}
    <div class="col-sm-6 col-lg-2 col-xl-2 col-6 d-flex">
        <div class="card invoices-grid-card w-100">
            <div class="card-header d-flex justify-content-between align-items-center">
                <a href="" class="invoice-grid-link"></a>
                <div class="dropdown dropdown-action">
                    <a href="#" class="action-icon dropdown-toggle sm" data-bs-toggle="dropdown"
                        aria-expanded="false"><i class="fas fa-ellipsis-v"></i></a>
                    <div class="dropdown-menu dropdown-menu-end">
                        <!-- <a class="dropdown-item" onclick="DataGets({{subcategory.id}})" data-bs-toggle="modal"
                            data-bs-target="#edit_subcategory"><i class="far fa-edit me-2"></i>Edit</a> -->
                        <a class="dropdown-item" onclick="deletesubcategory({{subcategory.id}})"><i class="far fa-trash-alt me-2"></i>Delete</a>
                    </div>
                </div>
            </div>
            <div class="card-middle text-center">
                <h2 class="card-middle-avatar text-center">
                    <a href="">
                        <p>{{subcategory.name}}</p>
                    </a>
                </h2>
            </div>
            <div class="card-footer">
                <div class="row align-items-center">
                    <div class="col-auto">
                        <a href="{% url 'web:product' subcategory.id %}" type="button"
                            class="btn btn-sm btn-block btn-outline-primary">Product</a>

                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

<!-- ADD CATEGORY -->
<div class="modal custom-modal fade invoices-preview" id="add_subcategory" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="card invoice-info-card">
                            <div class="card-header">
                                <h5 class="card-title">Add SubCategory</h5>
                            </div>
                            <div class="card-body pb-0">
                                <form action="#" method="POST">
                                    {% csrf_token %}
                                    <div class="form-group row">
                                        <label class="col-form-label col-md-4">SubCategory Name</label>
                                        <div class="col-md-8">
                                            <input type="text" class="form-control" name="subcat-name" id="cat_name"
                                                onchange="catageoryName()">
                                            <span id="catogry"></span>
                                        </div>
                                    </div>
                                    <div class="text-end mt-4">
                                        <button type="submit" class="btn btn-primary">Add Category</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- EDIT PRODUCT -->
<div class="modal custom-modal fade invoices-preview" id="edit_subcategory" role="dialog">
    <div class="modal-dialog modal-dialog-centered modal-md">
        <div class="modal-content">
            <div class="modal-body">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="card invoice-info-card">
                            <div class="card-header">
                                <h5 class="card-title">Edit Product</h5>
                            </div>
                            <div class="card-body pb-0">
                                <form action="#">
                                    {% csrf_token %}
                                    <div class="form-group row">
                                        <label class="col-form-label col-md-4">Product Name</label>
                                        <div class="col-md-8">
                                            <input type="text" id="fid" name="fid" hidden>
                                            <input type="text" class="form-control" value="butter shake" id="scname"
                                                name="scname">
                                        </div>
                                    </div>
                                    <div class="text-end mt-4">
                                        <button type="submit" class="btn btn-primary">Edit Product</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    function DataGets(id) {
        alert(id)
        $.ajax({
            url: "/web/getsubcategory/" + id,
            type: 'GET',

            success: function (responce) {
                $('#fid').val(id)
                $('#scname').val(responce.name)

            }

        })

    }

</script>

<script>
    function deletesubcategory(id) {
        Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!'
        }).then((result) => {
            if (result.isConfirmed) {
                Swal.fire(
                    'Deleted!',
                    'Your file has been deleted.',
                    'success'
                )
                window.location.href = "/web/deletesubcatgory/" + id
            }
        })
    }
</script>


{% endblock %}