aahalive/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("menucard/", include("menucard.urls")),
        path("", include("website.urls")),
        path("web/", include("web.urls")),
        path("official/", include("official.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

official/urls.py
from . import views
from django.urls import path


app_name = "official"

urlpatterns = [
    path("login-page", views.loginPage, name="loginPage"),
    path("logout-resto", views.logout_resto, name="logout_resto"),
    path("", views.home, name="home"),
    path("resturant_list", views.resturantList, name="resturant_list"),
    path("resturant_details/<int:id>", views.resturantDetails, name="resturant_details"),
    path("create_user", views.creatUsers, name="create_user"),
    path("banneradding", views.bannerPage, name="banneradding"),
    path("product-banner", views.productBanner, name="productbanner"),
    path("video", views.videoAdding, name="video"),
]

web/urls.py
from . import views
from django.urls import path


app_name = "web"

urlpatterns = [
    path("", views.home, name="home"),
    # catagory
    path("category", views.category, name="category"),
    path("categorynamevalidation", views.categoryNameValidation, name="categorynamevalidation"),
    path("getcategory/<int:id>", views.getCategory, name="getcategory"),
    path("editcategory", views.editCategory, name="editcategory"),
    path("deletecatgory/<int:id>", views.deleteCategory, name="deletecatgory"),
    # subcategory
    path("subcategory/<int:id>", views.subCategory, name="subcategory"),
    path("getsubcategory/<int:id>", views.getSubcategory, name="getsubcategory"),
    path("deletesubcatgory/<int:id>", views.deleteSubCategory, name="deletesubcatgory"),
    path("product/<int:id>", views.product, name="product"),
    path("product-show/<int:id>", views.productshow, name="productshow"),
    path("productinactive/<int:id>", views.productNotavailable, name="productinactive"),
    path("productactive/<int:id>", views.productavailable, name="productactive"),
    path("deleteproduct/<int:id>", views.deleteProduct, name="deleteproduct"),
    path("banner", views.banner, name="banner"),
    path("profile", views.profile, name="profile"),
    path("settings", views.settings, name="settings"),
    path("socialmedia", views.socialMedialinks, name="socialmedia"),
    # table
    path("table-On/<int:id>", views.tableOn, name="tableOn"),
    path("table-off/<int:id>", views.tableOff, name="tableOff"),
]

templates/web/partials/header.html
{% load static %}
<div class="header header-one">

    <div class="header-left header-left-one">
        <a href="" class="logo">
            <img src="{% static 'website/img/logo/Logo_TV_2015.png' %}" alt="Logo">
        </a>
        <a href="" class="white-logo">
            <img src="{% static 'website/img/logo/Logo_TV_2015.png' %}" alt="Logo">
        </a>
        <a href="" class="logo logo-small">
            <img src="{% static 'website/img/logo/Logo_TV_2015.png' %}" alt="Logo" width="30" height="30">
        </a>
    </div>


    <a href="javascript:void(0);" id="toggle_btn">
        <i class="fas fa-bars"></i>
    </a>


    <div class="top-nav-search">
        <form>
            <input type="text" class="form-control" placeholder="Search here">
            <button class="btn" type="submit"><i class="fas fa-search"></i></button>
        </form>
    </div>


    <a class="mobile_btn" id="mobile_btn">
        <i class="fas fa-bars"></i>
    </a>


    <ul class="nav nav-tabs user-menu">


        <li class="nav-item dropdown has-arrow main-drop">
            <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
                <span class="user-img">
                    <img src="{% static 'web/img/pro pic.png' %}" alt="">
                    <span class="status online"></span>
                </span>
                <span>{{restaurant.restaurant_name|capfirst}}</span>
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'web:profile' %}"><i data-feather="user" class="me-1"></i>
                    Profile</a>
                <a class="dropdown-item" href="{% url 'official:logout_resto' %}"><i data-feather="log-out" class="me-1"></i>
                    Logout</a>
            </div>
        </li>

    </ul>

</div>

templates/web/partials/sidebar.html
{% load static %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li class="menu-title"><span>Main</span></li>
                <li {% if is_home %} class="active" {% endif %}>
                    <a href="{% url 'web:home' %}"><i class="fa fa-home"></i><span>Dashboard</span></a>
                </li>
                <li {% if is_product %} class="active" {% endif %}>
                    <a href="{% url 'web:category' %}"><i class="fa fa-bowl-food"></i> <span>Products</span></a>
                </li>
                <li {% if all_banner %} class="active" {% endif %}>
                    <a href="{% url 'web:banner' %}"><i class="fa fa-signs-post"></i> Home Page Banner</a>
                </li>
                <li {% if is_profile %} class="active" {% endif %}>
                    <a href="{% url 'web:profile' %}"><i class="fa fa-user"></i> <span>Profile </span></a>
                </li>
                <li {% if is_links %} class="active" {% endif %}>
                    <a href="{% url 'web:socialmedia' %}"><i class="fa fa-user"></i> <span>Social Media Links </span></a>
                </li>
                <li {% if is_settings %} class="active" {% endif %}>
                    <a href="{% url 'web:settings' %}"><i class="fa fa-gear"></i> <span>Settings</span></a>
                </li>
            </ul>
        </div>
    </div>
</div>