aahalive/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path


urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("menucard/", include("menucard.urls")),
        path("", include("website.urls")),
        path("web/", include("web.urls")),
        path("official/", include("official.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

official/urls.py
from . import views
from django.urls import path


app_name = "official"

urlpatterns = [
    path("login-page", views.loginPage, name="loginPage"),
    path("logout-resto", views.logout_resto, name="logout_resto"),
    path("", views.home, name="home"),
    path("resturant_list", views.resturantList, name="resturant_list"),
    path("resturant_details/<int:id>", views.resturantDetails, name="resturant_details"),
    path("create_user", views.creatUsers, name="create_user"),
    path("banneradding", views.bannerPage, name="banneradding"),
    path("product-banner", views.productBanner, name="productbanner"),
    path("video", views.videoAdding, name="video"),
]

web/urls.py
from . import views
from django.urls import path


app_name = "web"

urlpatterns = [
    path("", views.home, name="home"),
    # catagory
    path("category", views.category, name="category"),
    path("categorynamevalidation", views.categoryNameValidation, name="categorynamevalidation"),
    path("getcategory/<int:id>", views.getCategory, name="getcategory"),
    path("editcategory", views.editCategory, name="editcategory"),
    path("deletecatgory/<int:id>", views.deleteCategory, name="deletecatgory"),
    # subcategory
    path("subcategory/<int:id>", views.subCategory, name="subcategory"),
    path("getsubcategory/<int:id>", views.getSubcategory, name="getsubcategory"),
    path("deletesubcatgory/<int:id>", views.deleteSubCategory, name="deletesubcatgory"),
    path("product/<int:id>", views.product, name="product"),
    path("product-show/<int:id>", views.productshow, name="productshow"),
    path("productinactive/<int:id>", views.productNotavailable, name="productinactive"),
    path("productactive/<int:id>", views.productavailable, name="productactive"),
    path("deleteproduct/<int:id>", views.deleteProduct, name="deleteproduct"),
    path("banner", views.banner, name="banner"),
    path("profile", views.profile, name="profile"),
    path("settings", views.settings, name="settings"),
    path("socialmedia", views.socialMedialinks, name="socialmedia"),
    # table
    path("table-On/<int:id>", views.tableOn, name="tableOn"),
    path("table-off/<int:id>", views.tableOff, name="tableOff"),
]

official/models.py
# Create your models here.

official/views.py
from aahalive.decorators import auth_official
from website.models import FrontBanner
from website.models import ProductPageBanner
from website.models import Restaurant
from website.models import Video

from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render


# Create your views here.


# LOGIN
def loginPage(request):
    if request.method == "POST":
        phone = request.POST["phone"]
        password = request.POST["password"]
        user = authenticate(request, phone=phone, password=password)
        if user is not None:
            if user.restaurant:
                login(request, user)
                return redirect("web:home")
            elif user.is_superuser:
                login(request, user)
                return redirect("official:home")
            else:
                return redirect("official:loginPage")
        else:
            return redirect("official:loginPage")
    return render(request, "official/login.html")


# HOME PAGE
@auth_official
@login_required(login_url="/official/login-page")
def home(request):
    resto_count = Restaurant.objects.all().count()
    all_resto = Restaurant.objects.all()[:5]
    banner = ProductPageBanner.objects.all()[:2]
    context = {"is_home": True, "resto_count": resto_count, "all_resto": all_resto, "banner": banner}
    return render(request, "official/home.html", context)


# RESTURANT LIST
@auth_official
@login_required(login_url="/official/login-page")
def resturantList(request):
    all_resturants = Restaurant.objects.all().order_by("restaurant_name")
    context = {"is_resto": True, "all_resturants": all_resturants}
    return render(request, "official/resturant_list.html", context)


# RESTURANT DETAILS
@auth_official
@login_required(login_url="/official/login-page")
def resturantDetails(request, id):
    resto_details = Restaurant.objects.get(id=id)
    data = {
        "resto_name": resto_details.restaurant_name,
        "creator_name": resto_details.creator_name,
        "email": resto_details.email,
        "phone": resto_details.phone,
        "district": resto_details.district,
        "state": resto_details.state,
        "address": resto_details.address,
    }
    return JsonResponse(data)


# USER CREATION
@auth_official
@login_required(login_url="/official/login-page")
def creatUsers(request):
    if request.method == "POST":
        cname = request.POST["cname"]
        email = request.POST["email"]
        district = request.POST["district"]
        rname = request.POST["rname"]
        phone = request.POST["phone"]
        state = request.POST["state"]
        address = request.POST["address"]
        password = request.POST["password"]

        resto_exist = Restaurant.objects.filter(phone=phone).exists()
        if not resto_exist:
            new_resto = Restaurant(creator_name=cname, restaurant_name=rname, email=email, phone=phone, password=password, district=district, state=state, address=address)
            new_resto.save()
            return render(request, "official/create_user.html", {"status": 1})
        else:
            return render(request, "official/create_user.html", {"status": 0})
    context = {"is_users": True}
    return render(request, "official/create_user.html", context)


# BANNER SECTION
@auth_official
@login_required(login_url="/official/login-page")
def bannerPage(request):
    if request.method == "POST":
        print("front-image")
        front_image = request.FILES["front-image"]
        front_banner = FrontBanner(image=front_image)
        front_banner.save()
    all_front_banner = FrontBanner.objects.all()
    all_product_banner = ProductPageBanner.objects.all()
    context = {"is_banner": True, "all_front_banner": all_front_banner, "all_product_banner": all_product_banner}
    return render(request, "official/banneradding.html", context)


# PRODUCT BANNER
@auth_official
@login_required(login_url="/official/login-page")
def productBanner(request):
    if request.method == "POST":
        product_image = request.FILES["product-image"]
        product_banner = ProductPageBanner(image=product_image)
        product_banner.save()
    return redirect("official:banneradding")


# VIDEO
def videoAdding(request):
    all_video = Video.objects.all()
    if request.method == "POST":
        video = request.FILES["video"]
        new_video = Video(video=video)
        new_video.save()
    context = {"is_video": True, "all_video": all_video}
    return render(request, "official/video.html", context)


# LOGOUT
def logout_resto(request):
    logout(request)
    return redirect("official:loginPage")

templates/official/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
    <title>Admin Dashboard</title>

    <link rel="shortcut icon" href="{% static 'menucard/images/logo/aha1.png' %}">
    <link rel="stylesheet" href="{% static 'web/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/plugins/fontawesome/css/fontawesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/plugins/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}">

</head>

<body class="nk-body bg-lighter npc-default has-sidebar no-touch nk-nio-theme">

    <div class="main-wrapper">

        {% include 'official/partials/header.html' %}

        {% include 'official/partials/sidebar.html' %}

        <div class="page-wrapper">
            <div class="content container-fluid">

                {% block content %}
                {% endblock %}

            </div>
        </div>
    </div>


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js' %}"></script>
    <script src="{% static 'web/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'web/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'web/js/feather.min.js' %}"></script>
    <script src="{% static 'web/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'web/plugins/apexchart/apexcharts.min.js' %}"></script>
    <script src="{% static 'web/plugins/apexchart/chart-data.js' %}"></script>
    <script src="{% static 'web/js/script.js' %}"></script>
</body>

</html>

templates/official/partials/header.html
{% load static %}
<div class="header header-one">

    <div class="header-left header-left-one">
        <a href="" class="logo">
            <img src="{% static 'menucard/images/logo/logo 124x70.png' %}" alt="Logo">
        </a>
        <a href="" class="white-logo">
            <img src="{% static 'menucard/images/logo/logo 124x70.png' %}" alt="Logo">
        </a>
        <a href="" class="logo logo-small">
            <img src="{% static 'menucard/images/logo/logo 124x70.png' %}" alt="Logo" width="30" height="30">
        </a>
    </div>


    <a href="javascript:void(0);" id="toggle_btn">
        <i class="fas fa-bars"></i>
    </a>


    <div class="top-nav-search">
        <form>
            <input type="text" class="form-control" placeholder="Search here">
            <button class="btn" type="submit"><i class="fas fa-search"></i></button>
        </form>
    </div>


    <a class="mobile_btn" id="mobile_btn">
        <i class="fas fa-bars"></i>
    </a>


    <ul class="nav nav-tabs user-menu">

        <!-- notifications -->
        <!-- <li class="nav-item dropdown">
            <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
                <i data-feather="bell"></i> <span class="badge rounded-pill">5</span>
            </a>
            <div class="dropdown-menu notifications">
                <div class="topnav-dropdown-header">
                    <span class="notification-title">Notifications</span>
                    <a href="javascript:void(0)" class="clear-noti"> Clear All</a>
                </div>
                <div class="noti-content">
                    <ul class="notification-list">
                        <li class="notification-message">
                            <a href="">
                                <div class="media d-flex">
                                    <span class="avatar avatar-sm">
                                        <img class="avatar-img rounded-circle" alt=""
                                            src="{% static 'web/img/profiles/avatar-02.jpg' %}">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">Brian Johnson</span>
                                            paid the invoice <span class="noti-title">#DF65485</span></p>
                                        <p class="noti-time"><span class="notification-time">4 mins ago</span>
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="activities.html">
                                <div class="media d-flex">
                                    <span class="avatar avatar-sm">
                                        <img class="avatar-img rounded-circle" alt=""
                                            src="{% static 'web/img/profiles/avatar-03.jpg' %}">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">Marie Canales</span>
                                            has accepted your estimate <span
                                                class="noti-title">#GTR458789</span></p>
                                        <p class="noti-time"><span class="notification-time">6 mins ago</span>
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="activities.html">
                                <div class="media d-flex">
                                    <div class="avatar avatar-sm">
                                        <span class="avatar-title rounded-circle bg-primary-light"><i
                                                class="far fa-user"></i></span>
                                    </div>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">New user
                                                registered</span></p>
                                        <p class="noti-time"><span class="notification-time">8 mins ago</span>
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="activities.html">
                                <div class="media d-flex">
                                    <span class="avatar avatar-sm">
                                        <img class="avatar-img rounded-circle" alt=""
                                            src="{% static 'web/img/profiles/avatar-04.jpg' %}">
                                    </span>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">Barbara Moore</span>
                                            declined the invoice <span class="noti-title">#RDW026896</span></p>
                                        <p class="noti-time"><span class="notification-time">12 mins ago</span>
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="notification-message">
                            <a href="activities.html">
                                <div class="media d-flex">
                                    <div class="avatar avatar-sm">
                                        <span class="avatar-title rounded-circle bg-info-light"><i
                                                class="far fa-comment"></i></span>
                                    </div>
                                    <div class="media-body">
                                        <p class="noti-details"><span class="noti-title">You have received a new
                                                message</span></p>
                                        <p class="noti-time"><span class="notification-time">2 days ago</span>
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="topnav-dropdown-footer">
                    <a href="activities.html">View all Notifications</a>
                </div>
            </div>
        </li> -->

        <li class="nav-item dropdown has-arrow main-drop">
            <a href="#" class="dropdown-toggle nav-link" data-bs-toggle="dropdown">
                <span class="user-img">
                    <img src="{% static 'web/img/pro.jpg' %}" alt="">
                    <span class="status online"></span>
                </span>
                <span>Admin</span>
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'web:profile' %}"><i data-feather="user" class="me-1"></i>
                    Profile</a>
                <a class="dropdown-item" href="{% url 'official:logout_resto' %}"><i data-feather="log-out" class="me-1"></i>
                    Logout</a>
            </div>
        </li>

    </ul>

</div>

templates/official/partials/sidebar.html
{% load static %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />



<div class="sidebar" id="sidebar">
    <div class="sidebar-inner slimscroll">
        <div id="sidebar-menu" class="sidebar-menu">
            <ul>
                <li class="menu-title"><span>Main</span></li>
                <li {% if is_home %} class="active" {% endif %}>
                    <a href="{% url 'official:home' %}"><i class="fa fa-home"></i> <span>Dashboard</span></a>
                </li>
                <li {% if is_resto %} class="active" {% endif %}>
                    <a href="{% url 'official:resturant_list' %}"><i class="fa fa-building"></i> <span>Resturants</span></a>
                </li>
                <li {% if is_users %} class="active" {% endif %}>
                    <a href="{% url 'official:create_user' %}"><i class="fa fa-users"></i> <span>Create User</span></a>
                </li>
                <li {% if is_banner %} class="active" {% endif %}>
                    <a href="{% url 'official:banneradding' %}"><i class="fa fa-signs-post"></i> <span>Banner Adding</span></a>
                </li>
                <li {% if is_video %} class="active" {% endif %}>
                    <a href="{% url 'official:video' %}"> <i class="fa fa-play"></i> <span>Upload Video</span></a>
                </li>
                <li {% if is_settings %} class="active" {% endif %}>
                    <a href=""><i class="fa fa-gear"></i> <span>Settings</span></a>
                </li>
            </ul>
        </div>
    </div>
</div>